services:
  - type: web
    name: nutrition-calculator
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nutrition-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: nutrition-db
    databaseName: nutrition_calculator
    user: nutrition_user